[target.xtensa-esp32s3-none-elf]
# runner = "probe-rs run --chip esp32s3"
runner = "espflash flash --monitor"

[env]
ESP_LOG="info"
ESP_HAL_PLACE_SPI_DRIVER_IN_RAM="true"

[build]
rustflags = [
  "-C", "link-arg=-Tlinkall.x",
  "-C", "link-arg=-nostartfiles",
]
target = "xtensa-esp32s3-none-elf"

[unstable]
build-std = ["core"]
