[package]
name = "firmware"
version = "0.1.0"
authors = ["Scott Mabin <scott@mabez.dev>"]
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
esp-hal = { features = ["esp32s3"], git = "https://github.com/bjoernQ/esp-hal", branch = "simplify-dma-usage"}
esp-backtrace = { version = "0.11.0", features = ["esp32s3", "panic-handler", "exception-handler", "println"] }
esp-println = { version = "0.9.0", default-features = false, features = ["esp32s3", "log", "jtag-serial"] }
log = { version = "0.4.20" }
static_cell = { version = "1", features = ["nightly"] }
embedded-graphics-core = "0.4.0"
critical-section = "1"

tinygif = "0.0.4"
embedded-graphics = "0.8.1"


[features]
# usb-pin-exchange is enabled by default for now, until we have a new revision of the hardware
# In the future we may wish to auto detect this based on either fw metadata
default = ["usb-pin-exchange"]
usb-pin-exchange = []

[profile.release]
codegen-units = 1 # LLVM can perform better optimizations using a single thread
debug = 2
debug-assertions = false
incremental = false
lto = 'fat'
opt-level = 's'
overflow-checks = false